language: node_js

node_js:
  - lts/*

services:
  - docker

install:
  - npm i

script:
  - npm run test -- --watch=false --browsers=ChromeHeadless
  - npm run e2e -- --protractor-config=./e2e/protractor.ci.conf.js
  - npm run build:ssr
  - docker build -t bkielczewski/kocioclock .

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
